#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)" || exit

# https://github.com/github/scripts-to-rule-them-all/tree/master/script

# Check/install prerequisites

# TODO: What versions of Ruby, Gem, Bundler, and so on?

# On a fresh Ubuntu Xenial container I did:
#
# ```
# sudo apt update
# sudo apt install git curl gcc libffi-dev ruby-ffi build-essential patch zlib1g-dev liblzma-dev ruby ruby-dev
# sudo gem install bundler
# ```
#
# On a used MacOS Sierra I did:
#
# ```
# brew install ruby
# sed -i .bak 's/\.gem\/ruby\/2\..\.0\/bin/\.gem\/ruby\/2\.4\.0\/bin/' ~/.bash_profile
# gem update
# ```

# Load dependencies

# This one was easy once I got all the prerequisite tools:
#
# ```
# bundle install --path vendor/bundle
# ```

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi
